env:
  matrix:
    - TZ=Europe/London
    - TZ=America/Los_Angeles

language: r
sudo: false
cache: packages

addons:
  apt:
    update: TRUE

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
