matrix:
    include:
        env: timezone=Europe/London
        env: timezone=America/Los_Angeles

befor_install:
  - export TZ=$timezone

language: r
sudo: false
cache: packages

addons:
  apt:
    update: TRUE

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
